### ISSUE TITLE
[Feature] Encrypted cloud backup (password)

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#425] opened 2020-06-09 15:16 UTC
See [parent](https://github.com/tari-project/tari/issues/1973)

**Comment by Tas4tari** [comment] 2020-07-03 08:40
@SerhiiShovkoplias Enter password screen to go in the Restore flow: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5ef40c39f47783a0be5cc238

**Comment by Tas4tari** [comment] 2020-07-03 08:45
i think we have to also input the existing password for a password change

i'm guessing it would just add another text field before the first one, but we need the copy for that one too

@SerhiiShovkoplias  the overlap may become a thing with this third text field:
https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5efed93db9928c41744f9b07

**Comment by Tas4tari** [comment] 2020-07-03 08:48
Video from @SerhiiShovkoplias : https://drive.google.com/file/d/1rzovxaMuTQDzzoPX74cu1A5oyXOJ9HBL/view

Response from Tal:
Looks great. Just two small things:

- The progress loader icon hangs for a while without any movement and then fills in all the way... Can we have it so it's never completely still? Like maybe its just a dot spinning inside or something if we're waiting for progress to start? Kind of like the one in Android that is always spinning
- Let's use the language "Backing up" instead of "backuping." I actually made a screen for you with the copy for this and the text below it, since I missed it in the spec: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5efed5f81c864776a3

c79cdf

**Comment by Tas4tari** [comment] 2020-07-03 09:02
**Received from Tal:**
As for the last case you guys brought up on standup today (@kutsal I think it was you who explained it?) around add/change pw and the next backup having to be tied together as far as success/failure, what do you think of retrying 3 times and then displaying the relevant error message while keeping user on the select password screen? This way they can resolve whatever the issue is and get back to that screen to try to save again once they return to the app.  If for whatever reason they close the app altogether and reopen it, they'll have to start over again, but it won't be unexpected because they never got the feedback that their password was successfully saved (or had any reason to think it might've been, e.g. if they were sent back to the prior screen)

**Comment by Tas4tari** [comment] 2020-07-15 06:48
@Jasonvdb @SerhiiShovkoplias Please see added requirement and design as discussed in stand up:
**Added Requirement:**
**Password Error message:**

- Error should only appear once first password field is no longer in focus (that is, once user taps out of it, usually in order to enter it again in the pw confirmation field)
- Design: http://zpl.io/VxzWw4X
cc @talmahaj

**Comment by Anziskavds** [comment] 2020-07-16 12:41
Tested on iOS on version 0.3.0 on an iPhone 7.

**Results:**
Enabled iCloud backups - User has not yet encrypted their wallet (Adding a Password): **Tested successfully** 

Please note that "Verify that the "Secure Your Backup" button is enabled as per the designs: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ef40bfefb40e1a33d60c236" tested successfully. There is no screenshot for this because I forgot to take one before I clicked on the button but it did test successfully.

**Screenshots:**
 
![IMG_0502.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/bb0ca923-8ef9-4ead-b5d0-c29d14cdfae6)

![IMG_0503.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/0f4519a2-1d88-4f33-b8b2-4b8031ebd0ed)

![IMG_0504.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/4cf7fcc3-80d2-4dec-9816-cc02c22369fc)

![IMG_0505.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/a3de0bdc-52d5-4c65-9eaf-03c124d4390c)

![IMG_0506.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/a3f89440-b73d-48ca-8dbe-ebc00fc64ba6)

![IMG_0507.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/8f067e6c-93f1-436e-af75-fe4f9b6f2880)

![IMG_0508.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/6d342614-14e9-468a-9678-1e6b2f9ebc5f)

![IMG_0509.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/cd2df3b7-8d48-4ee5-95bf-699357f9a92e)

![IMG_0510.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/9eda006c-17e9-4765-8944-77fabc3167de)

![IMG_0511.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/2bea923f-27dc-4dee-bc7d-f9a6976bb761)

**Comment by Anziskavds** [comment] 2020-07-16 12:47
Tested on iOS on version 0.3.0 on an iPhone 7.

**Results:**
Enabled iCloud backups - User has already encrypted their wallet (Changing a Password): **Tested successfully**

**Screenshots:**

![IMG_0512.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/199d8b10-dd36-4c04-b39f-408963256b9f)

![IMG_0513.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/ee93994e-a1aa-4d1a-9f9f-b4187f06ab5c)

![IMG_0514.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/9285c697-fa0a-43a4-8afb-feb1f07f2668)

![IMG_0515.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/154a3e03-0e90-4882-9a1a-dce698efeb9c)

![IMG_0516.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/c90e8435-ed59-497f-978b-7325202b7619)

![IMG_0517.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/8bbf617c-ed0f-4d91-a437-df0f83b22890)

![IMG_0518.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/05a07bfc-2736-43f2-837d-ab8c05248c0e)

![IMG_0519.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/c486be81-4d64-49cf-8768-139458092008)

![IMG_0520.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/d928f9dd-1c5c-4dac-b9ef-11baafe40a5f)

![IMG_0521.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/46dded9b-27f7-49d0-adb7-15db02bd9440)

![IMG_0522.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/d77a95f5-2c45-4f17-9cc6-0bb59a615b47)

![IMG_0523.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/a74a2518-8ee8-4e35-bbd9-b6b08c111c67)

![IMG_0524.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/12211e11-5630-4147-a733-b5340c3aef70)

![IMG_0526.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/5f34b33a-8bd5-41f4-b4e5-05eb6a7ce251)

![IMG_0527.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/a925e376-0746-40d1-9949-e021633b1e00)

**Comment by Anziskavds** [comment] 2020-07-16 13:23
Tested Disabled Backups and I found that the "Failed to create backup" error message doesn't have the writing below "Failed to create backup". It only pops up "Failed to create backup". I see on the video @SerhiiShovkoplias made https://drive.google.com/file/d/1rzovxaMuTQDzzoPX74cu1A5oyXOJ9HBL/view it has writhing below the "Failed to create backup" title. Which is correct? @Tas4tari @@talmahaj @kukabi @Jasonvdb

**Comment by Anziskavds** [comment] 2020-07-17 14:28
Tested on iOS on version 0.3.0 on an iPhone 7. There are a few issues found while testing this which separate tickets were created for each of them. Functionality tested successfully so I'm closing this ticket.

Separate issues found and added to Github:

https://github.com/tari-project/wallet-ios/issues/482
https://github.com/tari-project/wallet-ios/issues/484
https://github.com/tari-project/wallet-ios/issues/485
https://github.com/tari-project/wallet-ios/issues/486
https://github.com/tari-project/wallet-ios/issues/487
https://github.com/tari-project/wallet-ios/issues/488

cc @Tas4tari @SerhiiShovkoplias @Jasonvdb @kukabi @@talmahaj

**Closed by Anziskavds** 2020-07-17 14:28 UTC
