### ISSUE TITLE
Screen Recoding keeps on disabling by itself

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/wallet-ios#1146] opened 2024-09-19 15:58 UTC
**Describe the bug**
I am trying to record videos for the issues I have to log but the screen recording keeps on disabling by itself. I have killed the app and tried to enable screen recording agin but it keeps on diabling by itself. Videos are black.

**To Reproduce**
1. Go to setting
2. Scroll to screen recording
3. Enable the screen recording option
4. Try to record a video
5. Videos are black
6. Go back to settings
7. Click on screen recording
8. Screen recording disabled by itself

**Expected behavior**
Screen recording shpuld stay enabled when the user set it to be enabled.

**Screenshots**
Unable to get some footage because of this issue.

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 17.6.1
 - Browser & Version Nextnet v0.27.0 (b757)

**Comment by TruszczynskiA** [comment] 2024-09-20 07:36
Duplicate of #1147

**Closed by TruszczynskiA** 2024-09-20 07:36 UTC
