### ISSUE TITLE
User is unable to Delete their wallet

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/wallet-ios#1144] opened 2024-09-19 15:27 UTC
**Describe the bug**
When a user navigates to setting and click on "Delete your wallet" nothing happens when the user clicks on the button. 

**To Reproduce**
1. Go to settings
2. Scroll down to "Delete your wallet"
3. Click on the "Delete your wallet" button
4. Currently nothing happens when the user clicks on the "Delete your wallet" button

**Expected behavior**
User should be able to delete their wallet successfully

**Video**
https://drive.google.com/file/d/1rPxGKumx8tuyw6v4cHQPjkOCV4whuoZj/view?usp=sharing

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 17.6.1
 - Browser & Version Nextnet v0.27.0 (b757)

**Comment by TruszczynskiA** [comment] 2024-09-20 07:32
Duplicate of #1147

**Closed by TruszczynskiA** 2024-09-20 07:32 UTC
