### ISSUE TITLE
Implement key events for tracking in Matomo

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#261] opened 2020-04-09 01:42 UTC
See the events we can trigger via mobile at https://github.com/tari-project/wallet-android/wiki/Matomo-Event-Tracking

**Comment by Jasonvdb** [comment] 2020-04-28 11:14
@talmahaj for this one `User's transaction fails - Base Node issue`. This often isn't the case, a base node sync can fail but user can still send and receive txs from other peers

**Comment by Anziskavds** [comment] 2020-05-12 12:42
@Jasonvdb Can you maybe provide me with more information on what should be tested on this card, please?

cc @Tas4tari

**Comment by Anziskavds** [comment] 2020-05-12 13:54
Tested unsuccessfully on iOS. My events aren't tracking on Matomo. The last event that shows is from an Android device.

![image.png](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/592ab663-98bc-46f9-90d5-eb6193465a87)

![image.png](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/959244fa-62ed-4c9d-9645-eef0a03daa12)

**Comment by Jasonvdb** [comment] 2020-05-21 14:14
@Anziskavds was this tested in prod? For iOS events are not tracked in testflight

**Comment by Anziskavds** [comment] 2020-05-22 13:58
@Jasonvdb I tested from a Testflight version. I remember we discussed this in stand up one time but totally forgot to retest on Prod and move the ticket back to UAT. I am just in the process of testing something else on the Testflight version. I will uninstall on Monday and reinstall from App store and retest this.

**Comment by Anziskavds** [comment] 2020-06-03 07:54
Sorry, I forgot to leave a comment here. I have tested this on iOS last week in Prod and it tested unsuccessfully. There were no events showing on Matomo. @Jasonvdb

**Comment by talmahaj** [comment] 2020-06-05 03:46
@SerhiiShovkoplias @Jasonvdb pls help @Anziskavds troubleshoot when you can, thanks!

**Comment by Anziskavds** [comment] 2020-06-09 13:13
Tested successfully on iOS version 0.1.14. I was unable to test "Transaction Failed - Node Issue" and "Transaction Failed - Tor Issue". I confirmed with @Jasonvdb and he said this can't really be tested it's just something that sometimes happens. I went back and looked on Matomo if I could find any of the two event trackings but I was unable to find something for iOS. I went back up until the 20 May 2020.

Please see the testing results and screenshots: [https://app.zenhub.com/files/213589121/6760eca1-dceb-4744-9d2e-0ceabf5933a7/download](https://app.zenhub.com/files/213589121/6760eca1-dceb-4744-9d2e-0ceabf5933a7/download)

cc @talmahaj @Tas4tari @SerhiiShovkoplias

**Comment by Anziskavds** [comment] 2020-06-10 06:53
@Jasonvdb As per stand up yesterday, Tal said I need to mention it to you to have a look at why there wasn't any event tracking for failed transactions on Matomo. It might be that it doesn't track the failed transactions. Would you mind having a look when you are back from leave, please? I know you said it's not possible to test the failed transactions and its just something that sometimes happens but I had a look from yesterday up until the 20 May 2020 to look for any tracking of a fail transaction and I couldn't find anything for iOS. 

cc @talmahaj @Tas4tari

**Comment by Tas4tari** [comment] 2020-07-06 15:49
@Anziskavds This can be tested now

**Comment by Anziskavds** [comment] 2020-07-06 17:50
@Tas4tari I'm. not sure what you mean? This has been tested. I'm waiting for feedback from Tal to see if the event tracking names are fine for the reason that it's not as per the requirements but it reflects the same on both platforms where it didn't in the past.

https://docs.google.com/document/d/1r0uy5fDa-coD55vKLwzUL0bAP008fPQmiBHIV0qF_rY/edit?usp=sharing

**Comment by Tas4tari** [comment] 2020-07-07 06:30
@Anziskavds This ticket wasn't sitting in UAT, I moved it there from Up Next. I know you were testing this for naming conventions etc. Can you also comment on this ticket with testing results before closing

**Comment by Anziskavds** [comment] 2020-07-07 11:35
Tested successfully on iOS version 0.2.1 on an iPhone 7.

The event tracking names is the same on both platforms(iOS and Android) but the names aren't the same as per the requirements. I have confirmed with Tal if she's happy with it and said it looks great. 
Document with event names: https://docs.google.com/document/d/1r0uy5fDa-coD55vKLwzUL0bAP008fPQmiBHIV0qF_rY/edit?usp=sharing

Test Results screenshots:

![image.png](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/72aad0d7-09bb-4d28-8bce-7d94b3000eae)

![image.png](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/f4272d6c-c9f7-4c61-a34c-9c963afda0ed)

![image.png](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/759db982-acfc-4562-8032-41fd05fb2102)

![image.png](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/f980873a-113c-4492-877b-f309a7871d7a)

cc @talmahaj @Tas4tari

**Closed by Anziskavds** 2020-07-07 11:35 UTC
