### ISSUE TITLE
Information icon is not clickable

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/wallet-ios#1145] opened 2024-09-19 15:53 UTC
**Describe the bug**
The information icon next to the emoji ID address is not clickable. Nothing happens when the user clicks on the icon.

**To Reproduce**
1. Click on the "My profile" button(the round button with the first emoji of your address)
2. Click on the "i" button next to the emoji ID address
3. The icon is not clickable

**Expected behavior**
User should see the window with their full addresses when they click on the "i" icon.

**Screenshots**
I am unable to get a video. The screen recording keeps on disabling by itself. Videos are black.

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 17.6.1
 - Browser & Version Nextnet v0.27.0 (b757)

**Comment by TruszczynskiA** [comment] 2024-09-20 07:31
Duplicate of #1147

**Closed by TruszczynskiA** 2024-09-20 07:31 UTC
