### ISSUE TITLE
[Feature] Add other cloud backup options, e.g. dropbox

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#424] opened 2020-06-09 15:02 UTC
@talmahaj commented on [Tue Jun 09 2020](https://github.com/tari-project/wallet-android/issues/428)

See [parent](https://github.com/tari-project/tari/issues/1972)

**Comment by Tas4tari** [comment] 2020-07-09 06:40
@talmahaj Moving this to Backlog as well

**Comment by TruszczynskiA** [comment] 2022-11-18 11:27
Duplicate of https://github.com/tari-project/wallet-ios/issues/785

**Closed by TruszczynskiA** 2022-11-18 11:27 UTC
